### PR TITLE
fix of SHP vehicle facing

### PR DESCRIPTION
**Pull request by CaconCaco**
issues: 
the current way only considers 8 facing. However Ares allows 16 32 or even more.

### CODE REVIEW

**Comment by AutoGavy** [comment]
挖藕

**Comment by secsome** [comment]
> 挖藕
不许挖藕

**Comment by AutoGavy** [comment]
挖伸

**Comment by CaconCaco** [comment]
挖打伸

**Comment by secsome** [comment]
Fixed. But close this PR for turret isn't included in it here

**Pull request closed without merging**
